version: '3.3'

services:
  user_db:
    image: mysql:latest
    container_name: ouioui_user_db
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=user_database
      - MYSQL_TCP_PORT=8001
    ports:
      - 8001:8001
    networks:
      - user-mysql

  user_ms:
    image: openjdk:latest
    networks:
      - user-mysql
    restart: on-failure
    container_name: ouioui_user_ms
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - user_db
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=ouioui_user_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=user_database
      - DATABASE_PORT=8001

networks:
  user-mysql: